server:
  port: 8010
spring:
  application:
    name: common-service
feign:
  hystrix:
    enabled: true
ribbon: 
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
