server:
  port: 8010
  max-http-header-size=10000000
spring:
  application:
    name: common-service
feign:
  hystrix:
    enabled: true
    hystrix:
	shareSecurityContext: true
	command:
	    default:
	        circuitBreaker:
		    sleepWindowInMilliseconds: 100000
		    forceClosed: true
	        execution:
		    isolation:
		        thread:
		            timeoutInMilliseconds: 600000
