server:
  port: 8010
  max-http-header-size: 10000000
  tomcat:
      max-http-post-size: 10000000
spring:
  application:
    name: common-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端
feign:
  hystrix:
    enabled: false
ribbon:
    ReadTimeout: 61000
    ConnectTimeout: 61000

