server:
  port: 8010
  max-http-header-size: 10000000
  tomcat:
      max-http-post-size: 10000000
spring:
  application:
    name: common-service
feign:
  hystrix:
    enabled: false
ribbon:
    ReadTimeout: 61000
    ConnectTimeout: 61000

